// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAClk4uKOZ7g8ujeCR4vMuXtwiHWJbDF_s',
    appId: '1:293882735832:web:f8a10263bf078085787bad',
    messagingSenderId: '293882735832',
    projectId: 'tesis2024-ee2bc',
    authDomain: 'tesis2024-ee2bc.firebaseapp.com',
    storageBucket: 'tesis2024-ee2bc.appspot.com',
    measurementId: 'G-Z20J6WM9XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIoxKn4KQZYtyoa1pC8nLsoH8GxgyLVew',
    appId: '1:293882735832:android:de2b5a7e7a984df6787bad',
    messagingSenderId: '293882735832',
    projectId: 'tesis2024-ee2bc',
    storageBucket: 'tesis2024-ee2bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sP14QexPaJ7In-noICVAbIzZ_PQkpYY',
    appId: '1:293882735832:ios:f3963c75b0d9bce7787bad',
    messagingSenderId: '293882735832',
    projectId: 'tesis2024-ee2bc',
    storageBucket: 'tesis2024-ee2bc.appspot.com',
    androidClientId: '293882735832-rq48kfnnmfd9h6h07idbkqjls7a9eeg7.apps.googleusercontent.com',
    iosClientId: '293882735832-7v7p9bbtks292c4hde1th9e5fbfehqdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesis3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8sP14QexPaJ7In-noICVAbIzZ_PQkpYY',
    appId: '1:293882735832:ios:f3963c75b0d9bce7787bad',
    messagingSenderId: '293882735832',
    projectId: 'tesis2024-ee2bc',
    storageBucket: 'tesis2024-ee2bc.appspot.com',
    androidClientId: '293882735832-rq48kfnnmfd9h6h07idbkqjls7a9eeg7.apps.googleusercontent.com',
    iosClientId: '293882735832-7v7p9bbtks292c4hde1th9e5fbfehqdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesis3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAClk4uKOZ7g8ujeCR4vMuXtwiHWJbDF_s',
    appId: '1:293882735832:web:02c105dc52a52523787bad',
    messagingSenderId: '293882735832',
    projectId: 'tesis2024-ee2bc',
    authDomain: 'tesis2024-ee2bc.firebaseapp.com',
    storageBucket: 'tesis2024-ee2bc.appspot.com',
    measurementId: 'G-GPCG6N81QC',
  );

}